# This is actually a Swift-project.
language: objective-c
osx_image: xcode8.2
script:
    - xcodebuild -project AccessibilityExamples.xcodeproj -scheme AccessibilityExamples -sdk iphonesimulator10.2 build

